<?php
/**
 * Casino data and quiz configuration.
 */
class Casino_Finder_Data {

    /**
     * Get quiz step definitions.
     */
    public static function get_steps() {
        $steps = array(
            array(
                'id'       => 'casino-type',
                'title'    => 'Type of Casino',
                'question' => 'What type of casino are you looking for?',
                'options'  => array(
                    array( 'label' => 'Online Casino', 'value' => 'online',       'icon' => '🎰' ),
                    array( 'label' => 'Sweepstakes',   'value' => 'sweepstakes',  'icon' => '🎟️' ),
                    array( 'label' => 'Social Casino', 'value' => 'social',       'icon' => '👥' ),
                    array( 'label' => 'No Deposit',    'value' => 'no-deposit',   'icon' => '🎁' ),
                    array( 'label' => 'Fast Paying',   'value' => 'fast-paying',  'icon' => '⚡' ),
                ),
            ),
            array(
                'id'       => 'game',
                'title'    => 'Preferred Game',
                'question' => 'What type of game do you prefer?',
                'options'  => array(
                    array( 'label' => 'Slots',       'value' => 'slots',       'icon' => '🎰' ),
                    array( 'label' => 'Blackjack',   'value' => 'blackjack',   'icon' => '🃏' ),
                    array( 'label' => 'Live Dealer', 'value' => 'live-dealer', 'icon' => '🎥' ),
                    array( 'label' => 'Table Games', 'value' => 'table-games', 'icon' => '🎲' ),
                ),
            ),
            array(
                'id'       => 'banking',
                'title'    => 'Deposit Method',
                'question' => 'What is your preferred deposit method?',
                'options'  => array(
                    array( 'label' => 'Credit Card',           'value' => 'credit-card',   'icon' => '💳' ),
                    array( 'label' => 'PayPal',                'value' => 'paypal',         'icon' => '🅿️' ),
                    array( 'label' => 'Crypto',                'value' => 'crypto',         'icon' => '₿' ),
                    array( 'label' => 'Apple Pay / Google Pay', 'value' => 'mobile-wallet', 'icon' => '📱' ),
                ),
            ),
            array(
                'id'       => 'payout',
                'title'    => 'Payout Speed',
                'question' => 'How fast do you want your payouts?',
                'options'  => array(
                    array( 'label' => 'Instant',      'value' => 'instant',       'icon' => '⚡' ),
                    array( 'label' => '1–2 Days',     'value' => '1-2-days',      'icon' => '🕐' ),
                    array( 'label' => 'Up to 1 Week', 'value' => 'up-to-1-week',  'icon' => '📅' ),
                ),
            ),
        );

        return apply_filters( 'casino_finder_steps', $steps );
    }

    /**
     * Get casino data set.
     */
    public static function get_casinos() {
        $casinos = array(
            array(
                'id'            => 'betmgm',
                'name'          => 'BetMGM Casino',
                'slug'          => 'betmgm-casino',
                'logo'          => 'betmgm.svg',
                'rating'        => 4.9,
                'review_url'    => '/reviews/betmgm-casino/',
                'affiliate_url' => 'https://www.betmgm.com',
                'promo_code'    => 'BETMGM100',
                'bonus_text'    => '100% deposit match up to $1,000 + $25 no-deposit bonus',
                'slot_games'    => 2000,
                'has_packages'  => true,
                'has_vip'       => true,
                'types'         => array( 'online', 'fast-paying' ),
                'games'         => array( 'slots', 'blackjack', 'live-dealer', 'table-games' ),
                'banking'       => array( 'credit-card', 'paypal', 'mobile-wallet' ),
                'payout_speed'  => 'instant',
            ),
            array(
                'id'            => 'draftkings',
                'name'          => 'DraftKings Casino',
                'slug'          => 'draftkings-casino',
                'logo'          => 'draftkings.svg',
                'rating'        => 4.8,
                'review_url'    => '/reviews/draftkings-casino/',
                'affiliate_url' => 'https://www.draftkings.com',
                'promo_code'    => 'DKPLAY',
                'bonus_text'    => 'Up to $50 in casino credits + 100% deposit match up to $2,000',
                'slot_games'    => 1500,
                'has_packages'  => true,
                'has_vip'       => true,
                'types'         => array( 'online', 'fast-paying' ),
                'games'         => array( 'slots', 'blackjack', 'live-dealer', 'table-games' ),
                'banking'       => array( 'credit-card', 'paypal', 'mobile-wallet' ),
                'payout_speed'  => 'instant',
            ),
            array(
                'id'            => 'caesars',
                'name'          => 'Caesars Casino',
                'slug'          => 'caesars-casino',
                'logo'          => 'caesars.svg',
                'rating'        => 4.7,
                'review_url'    => '/reviews/caesars-casino/',
                'affiliate_url' => 'https://www.caesars.com/casino',
                'promo_code'    => 'CAESAR200',
                'bonus_text'    => '100% deposit match up to $1,250 + 2,500 reward credits',
                'slot_games'    => 1200,
                'has_packages'  => true,
                'has_vip'       => true,
                'types'         => array( 'online' ),
                'games'         => array( 'slots', 'blackjack', 'live-dealer', 'table-games' ),
                'banking'       => array( 'credit-card', 'paypal' ),
                'payout_speed'  => '1-2-days',
            ),
            array(
                'id'            => 'fanduel',
                'name'          => 'FanDuel Casino',
                'slug'          => 'fanduel-casino',
                'logo'          => 'fanduel.svg',
                'rating'        => 4.7,
                'review_url'    => '/reviews/fanduel-casino/',
                'affiliate_url' => 'https://www.fanduel.com/casino',
                'promo_code'    => 'FDCASINO',
                'bonus_text'    => 'Play it again up to $1,000 + 50 bonus spins',
                'slot_games'    => 1800,
                'has_packages'  => true,
                'has_vip'       => false,
                'types'         => array( 'online', 'fast-paying' ),
                'games'         => array( 'slots', 'blackjack', 'live-dealer', 'table-games' ),
                'banking'       => array( 'credit-card', 'paypal', 'mobile-wallet' ),
                'payout_speed'  => 'instant',
            ),
            array(
                'id'            => 'bet365',
                'name'          => 'bet365 Casino',
                'slug'          => 'bet365-casino',
                'logo'          => 'bet365.svg',
                'rating'        => 4.6,
                'review_url'    => '/reviews/bet365-casino/',
                'affiliate_url' => 'https://www.bet365.com',
                'promo_code'    => 'BET365C',
                'bonus_text'    => 'Up to $500 new player bonus + 100 free spins',
                'slot_games'    => 900,
                'has_packages'  => false,
                'has_vip'       => true,
                'types'         => array( 'online' ),
                'games'         => array( 'slots', 'blackjack', 'live-dealer', 'table-games' ),
                'banking'       => array( 'credit-card', 'paypal', 'crypto', 'mobile-wallet' ),
                'payout_speed'  => '1-2-days',
            ),
            array(
                'id'            => 'borgata',
                'name'          => 'Borgata Casino',
                'slug'          => 'borgata-casino',
                'logo'          => 'borgata.svg',
                'rating'        => 4.5,
                'review_url'    => '/reviews/borgata-casino/',
                'affiliate_url' => 'https://www.borgataonline.com',
                'promo_code'    => 'BORGATA20',
                'bonus_text'    => '$20 no-deposit bonus + 100% deposit match up to $1,000',
                'slot_games'    => 1100,
                'has_packages'  => true,
                'has_vip'       => true,
                'types'         => array( 'online', 'no-deposit' ),
                'games'         => array( 'slots', 'blackjack', 'table-games' ),
                'banking'       => array( 'credit-card', 'paypal' ),
                'payout_speed'  => '1-2-days',
            ),
            array(
                'id'            => 'playstar',
                'name'          => 'PlayStar Casino',
                'slug'          => 'playstar-casino',
                'logo'          => 'playstar.svg',
                'rating'        => 4.3,
                'review_url'    => '/reviews/playstar-casino/',
                'affiliate_url' => 'https://www.playstarcasino.com',
                'promo_code'    => 'PSTAR500',
                'bonus_text'    => '100% deposit match up to $500 + 25 free spins',
                'slot_games'    => 800,
                'has_packages'  => false,
                'has_vip'       => true,
                'types'         => array( 'online', 'no-deposit' ),
                'games'         => array( 'slots', 'blackjack', 'live-dealer' ),
                'banking'       => array( 'credit-card', 'mobile-wallet' ),
                'payout_speed'  => '1-2-days',
            ),
            array(
                'id'            => 'stakeus',
                'name'          => 'Stake.us',
                'slug'          => 'stake-us',
                'logo'          => 'stakeus.svg',
                'rating'        => 4.4,
                'review_url'    => '/reviews/stake-us/',
                'affiliate_url' => 'https://www.stake.us',
                'promo_code'    => 'STAKEVIP',
                'bonus_text'    => '25 Stake Cash + 250,000 Gold Coins on signup',
                'slot_games'    => 600,
                'has_packages'  => true,
                'has_vip'       => true,
                'types'         => array( 'sweepstakes' ),
                'games'         => array( 'slots', 'blackjack', 'table-games' ),
                'banking'       => array( 'crypto', 'mobile-wallet' ),
                'payout_speed'  => 'instant',
            ),
            array(
                'id'            => 'mcluck',
                'name'          => 'McLuck',
                'slug'          => 'mcluck',
                'logo'          => 'mcluck.svg',
                'rating'        => 4.2,
                'review_url'    => '/reviews/mcluck/',
                'affiliate_url' => 'https://www.mcluck.com',
                'promo_code'    => 'MCLUCK50',
                'bonus_text'    => '57,500 Gold Coins + 27.5 Sweepstakes Coins free',
                'slot_games'    => 500,
                'has_packages'  => true,
                'has_vip'       => false,
                'types'         => array( 'sweepstakes', 'no-deposit' ),
                'games'         => array( 'slots', 'table-games' ),
                'banking'       => array( 'credit-card', 'crypto', 'mobile-wallet' ),
                'payout_speed'  => '1-2-days',
            ),
            array(
                'id'            => 'wowvegas',
                'name'          => 'WOW Vegas',
                'slug'          => 'wow-vegas',
                'logo'          => 'wowvegas.svg',
                'rating'        => 4.1,
                'review_url'    => '/reviews/wow-vegas/',
                'affiliate_url' => 'https://www.wowvegas.com',
                'promo_code'    => 'WOWFREE',
                'bonus_text'    => '1.5 million WOW Coins + 30 free Sweepstakes Coins',
                'slot_games'    => 700,
                'has_packages'  => true,
                'has_vip'       => false,
                'types'         => array( 'sweepstakes', 'no-deposit' ),
                'games'         => array( 'slots' ),
                'banking'       => array( 'credit-card', 'crypto' ),
                'payout_speed'  => '1-2-days',
            ),
            array(
                'id'            => 'high5',
                'name'          => 'High 5 Casino',
                'slug'          => 'high-5-casino',
                'logo'          => 'high5.svg',
                'rating'        => 4.0,
                'review_url'    => '/reviews/high-5-casino/',
                'affiliate_url' => 'https://www.high5casino.com',
                'promo_code'    => 'HIGH5GC',
                'bonus_text'    => '250 Game Coins + 5 Sweeps Coins + 600 Diamonds free',
                'slot_games'    => 450,
                'has_packages'  => false,
                'has_vip'       => false,
                'types'         => array( 'social', 'no-deposit' ),
                'games'         => array( 'slots', 'table-games' ),
                'banking'       => array( 'credit-card', 'paypal' ),
                'payout_speed'  => 'up-to-1-week',
            ),
            array(
                'id'            => 'realprize',
                'name'          => 'RealPrize',
                'slug'          => 'realprize',
                'logo'          => 'realprize.svg',
                'rating'        => 3.9,
                'review_url'    => '/reviews/realprize/',
                'affiliate_url' => 'https://www.realprize.com',
                'promo_code'    => 'RPRIZE',
                'bonus_text'    => '10 free Sweepstakes Coins on registration',
                'slot_games'    => 300,
                'has_packages'  => false,
                'has_vip'       => false,
                'types'         => array( 'sweepstakes', 'social', 'no-deposit' ),
                'games'         => array( 'slots' ),
                'banking'       => array( 'credit-card', 'crypto' ),
                'payout_speed'  => 'up-to-1-week',
            ),
        );

        return apply_filters( 'casino_finder_casinos', $casinos );
    }

    /**
     * Get full config object for wp_localize_script.
     */
    public static function get_config() {
        $config = array(
            'steps'            => self::get_steps(),
            'casinos'          => self::get_casinos(),
            'loading_messages' => array(
                'Selecting the best type of casino...',
                'Finding your preferred games...',
                'Analyzing deposit and payout options...',
            ),
            'no_results_message' => "We couldn't find a match. Try different options!",
            'results_intro'      => 'Out of {total} casinos researched, these align with your preferences.',
            'plugin_url'         => CF_URL,
        );

        return apply_filters( 'casino_finder_config', $config );
    }
}
